 ### Hypothesis: The amount of solid food Beren consumes has increased over time
Solids<−which(beren3$event=="solids")
totalSolids<−tapply(beren3$value[solids],beren3$age[solids],sum)
numSolids<−tapply(beren3$value[Solids],beren3$age[Solids],length)
cor(beren3$value[Solids],beren3$age[Solids],use = "complete.obs")
cor.test(beren3$value[Solids],beren3$age[Solids])
berenCorTest<-cor.test(beren3$value[Solids],beren3$age[Solids])
par(las=1, mar=c (5 ,5,1,1),mgp=c(2,0.5,0),tck=−0.01)
plot(as.numeric(names(totalSolids)),totalSolids,type="b",pch=16,xlab="Age in days",ylab="Solid food consumed")
abline(h=mean(totalSolids),lty=2,col='red')
pdf("r02c−totalSolidsPerDay.pdf",height=6,width=6)
par(las=1,mar=c(5,5,1,1),mgp=c(2,0.5,0),tck=−0.01)
plot(as.numeric(names(totalSolids)),totalSolids,type="b",pch=16,xlab="Age in days",ylab="Solid food consumed")
abline(h=mean(totalSolids),lty=2,col='red')
dev.off( )